#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

if [ "${BASH_SOURCE:-}" == "${0}" ]; then 
    echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh" 
    exit 1 
fi 

 export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}/home/ns3-dce/bake/build/lib"
 export PATH="${PATH:+${PATH}:}/home/ns3-dce/bake/build/bin"
 export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}/home/ns3-dce/bake:/home/ns3-dce/bake/build/lib:/home/ns3-dce/bake/build/lib/python3/dist-packages"
 export INSTALL_BASE=/home/ns3-dce/bake/build
